//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneSystem
{
    using FortuneSystem.Models.Catalogos;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text.RegularExpressions;
    using System.Web;

    public partial class IMAGEN_ARTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMAGEN_ARTE()
        {
            this.ARTE = new HashSet<ARTE>();
        }
        [Display(Name = "ARTE#")]
        public int IdImgArte { get; set; }
        public Nullable<int> IdEstilo { get; set; }
        [Display(Name = "STATE ART")]
        public Nullable<int> StatusArte { get; set; }
        [Display(Name = "STATE PNL")]
        public Nullable<int> StatusPNL { get; set; }
        [Display(Name = "ART IMAGE")]
        public byte[] imgArte { get; set; }
        [Display(Name = "PNL IMAGE")]
        public byte[] imgPNL { get; set; }
        [Display(Name = "CUSTOMER")]
        public string Tienda { get; set; }
        public HttpPostedFileBase FileArte { get; set; }
        public HttpPostedFileBase FilePNL { get; set; }
        public EstatusArte EstadosArte { get; set; }
        public EstatusPNL EstadosPNL { get; set; }
        public List<CatTallaItem> ListaTallas { get; set; }
        [Display(Name = "STYLE")]
        public string Estilo { get; set; }
        [Display(Name = "DESCRIPTION")]
        public string DescripcionEstilo { get; set; }
        public MatchCollection ResultadoK { get; set; }
        public MatchCollection ResultadoW { get; set; }
        public virtual ARTE CATARTE { get; set; }
        public string PO { get; set; }
        public string extensionArte { get; set; }
        public string extensionPNL { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ARTE> ARTE { get; set; }
        public virtual IMAGEN_ARTE_PNL IMAGEN_ARTE_PNL { get; set; }
        public string StatusArteInf { get; set; }
        //Tecnicas de especialidades
        public virtual CatEspecialidades CatEspecialidades { get; set; }
        public List<CatEspecialidades> ListaTecnicas { get; set; }
        //public DateTime Fecha { get; set; }
        public string FechaArte { get; set; }
        public string Color { get; set; }
        [Display(Name = "COMBOS ART")]
        public string combos { get; set; }
        [Display(Name = "COMENTS")]
        public string comentarios { get; set; }
        public Nullable<int> idUsuario { get; set; }
    }
    public enum EstatusArte
    {
        APPROVED = 1,
        REVIEWED = 2,
        PENDING = 3,
        INHOUSE = 4
    }
    public enum EstatusPNL
    {
        APPROVED = 1,
        INHOUSE = 2,
        REVIEWED = 3,
        PENDING = 4
    }
}
