//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPC
    {
        public int IdUPC { get; set; }
        public Nullable<int> IdTalla { get; set; }
        public Nullable<int> IdSummary { get; set; }
        public Nullable<long> UPC1 { get; set; }
        public Nullable<int> IdEstilo { get; set; }
        public string Talla { get; set; }
    }
}
